export const GET_PERSONAJES = "GET_PERSONAJE"
export const GET_PERSONAJES_OK = "GET_PERSONAJE_OK"
export const GET_PERSONAJES_FAIL = "GET_PERSONAJE_FAIL"



// perrsoanjes unicos 
export const GET_SINGLE_PERSONAJE = "GET_SINGLE_PERSONAJE"
export const GET_SINGLE_PERSONAJE_OK = "GET_SINGLE_PERSONAJE_OK"
export const GET_SINGLE_PERSONAJE_FAIL = "GET_SINGLE_PERSONAJE_FAIL"

