export const GET_CRONOLOGIAS = "GET_CRONOLOGIA"
export const GET_CRONOLOGIAS_OK = "GET_CRONOLOGIA_OK"
export const GET_CRONOLOGIAS_FAIL = "GET_CRONOLOGIA_FAIL"

// segundo link single // boyon agreagar 

export const AGREGAR_CRONOLOGIA = 'AGREGAR_CRONOLOGIA';
export const AGREGAR_CRONOLOGIA_OK = 'AGREGAR_CRONOLOGIA_OK';
export const AGREGAR_CRONOLOGIA_FAIL = 'AGREGAR_CRONOLOGIA_FAIL';

// boton eliminar 

export const ELIMINAR_CRONOLOGIA = 'ELIMINAR_CRONOLOGIA';
export const ELIMINAR_CRONOLOGIA_OK = 'ELIMINAR_CRONOLOGIA_OK';
export const ELIMINAR_CRONOLOGIA_FAIL = 'ELIMINAR_CRONOLOGIA_FAIL';


